name: BlockBreaker.net RPG
version: 1.0
description: RPG Plugin des BlockBreaker Servers
author: lusu007
authors: [Blackagent]

main: net.blockbreaker.rpg.system.Main
load: POSTWORLD
depend: [MySQL_Management]
